---
language: python
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -y -n test-environment python=3.5
  - source activate test-environment
  - conda install -q -y -n test-environment numpy scipy pytest pandas pytables xarray toolz
  - conda install -q -y -n test-environment cython matplotlib jupyter click pytest-cov
  - conda install -q -y -n test-environment scikit-image
  - conda install --channel conda-forge -q -y -n test-environment vega
  - pip install sumatra scikit-fmm pylint datreant.core yamlmagic PyYAML nbval
  - git clone https://github.com/usnistgov/fipy.git ~/fipy
  - cd ~/fipy
  - 2to3 --write .
  - python setup.py install
  - cd $TRAVIS_BUILD_DIR
  - pip install .
script:
  - py.test
  - pylint extremefill2D/fextreme
