---
language: python
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -y -n test-environment python=3
  - source activate test-environment
  - conda install -q -y -n test-environment numpy scipy pytest pandas pytables
  - conda install -q -y -n test-environment cython matplotlib
  - pip install sumatra
  - git clone https://github.com/usnistgov/fipy.git ~/fipy;
  - cd ~/fipy;
  - 2to3 --write .
  - 2to3 --write --doctests_only .
  - python setup.py install;
  - cd $TRAVIS_BUILD_DIR;
  - pip install .
script:
  - py.test
