#!/bin/bash

# default
QSUBDIR=.qsub
CFL=0.1
NX=300
TOL=1e-10
SWEEPS=4
SOLVER_TOL=1e-6
AREA_RATIO=0.093
KPLUS=100.
KMINUS=2.45e7
FEATUREDEPTH=56e-6
DELTAREF=0.03
DTMAX=1.
TOTALTIME=7000

# non-default
SERIALNUMBER=20

for NX in 300 600 1200
do
    for DELTAREF in 0.001 0.005 0.01 0.02 0.03 0.04
    do
	qsub -cwd -o $QSUBDIR -e $QSUBDIR launcher \
	    --tag=qsub \
	    --tag=serialnumber$SERIALNUMBER \
	    --reason="Rerun featureDepth simulations as parameter was not passed." \
	    --totalSteps=100000000000 \
	    --CFL=$CFL \
	    --Nx=$NX \
	    --sweeps=$SWEEPS \
	    --tol=$TOL \
	    --solver_tol=$SOLVER_TOL \
	    --areaRatio=$AREA_RATIO \
	    --kPlus=$KPLUS \
	    --kMinus=$KMINUS \
	    --featureDepth=$FEATUREDEPTH \
	    --deltaRef=$DELTAREF \
	    --dtMax=$DTMAX \
            --totalTime=$TOTALTIME
    done
done